tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: hero
            field:
              max_files: 1
              mode: list
              container: images
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Hero
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: featured
            field:
              default: false
              type: toggle
              display: Featured
              icon: toggle
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: summary
            field:
              antlers: false
              type: textarea
              display: Summary
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: content
            field:
              type: markdown
              localizable: true
          -
            handle: links
            field:
              fields:
                -
                  handle: type
                  field:
                    options:
                      github: GitHub
                      figma: Figma
                      website: Website
                    taggable: false
                    push_tags: false
                    multiple: false
                    clearable: false
                    searchable: true
                    cast_booleans: false
                    type: select
                    display: Type
                    icon: select
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
                -
                  handle: url
                  field:
                    input_type: url
                    antlers: false
                    type: text
                    display: URL
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
              mode: stacked
              reorderable: true
              fullscreen: true
              type: grid
              display: Links
              icon: grid
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
          -
            handle: date
            field:
              type: date
              required: true
              default: now
              validate:
                - required
          -
            handle: parent
            field:
              type: entries
              collections:
                - projects
              max_items: 1
              listable: false
              localizable: true
title: Project
